-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module AbsJavalette where

newtype Ident = Ident String
  deriving (Eq, Ord, Show, Read)

data Prog = Program [TopDef]
  deriving (Eq, Ord, Show, Read)

data TopDef
    = TopDefFun Fun | TopDefStruct Struct | TopDefPointer Pointer
  deriving (Eq, Ord, Show, Read)

data Fun
    = FnDef Type Ident [Arg] Blk | PFnDef Ident Ident [Arg] Blk
  deriving (Eq, Ord, Show, Read)

data Arg = Argument Type Ident | PArgument Ident Ident
  deriving (Eq, Ord, Show, Read)

data Struct = StructDef Ident [Attribute]
  deriving (Eq, Ord, Show, Read)

data Attribute = Attr Type Ident | PAttr Ident Ident
  deriving (Eq, Ord, Show, Read)

data Pointer = PointerDef Ident Ident
  deriving (Eq, Ord, Show, Read)

data Blk = Block [Stmt]
  deriving (Eq, Ord, Show, Read)

data Stmt
    = Empty
    | BStmt Blk
    | Decl Type [Item]
    | PDecl Ident [Item]
    | Ass Ident Expr
    | AssElem Expr Expr
    | Incr Ident
    | Decr Ident
    | ReturnE Expr
    | ReturnV
    | Cond Expr Stmt
    | CondElse Expr Stmt Stmt
    | While Expr Stmt
    | ForEach Type Ident Expr Stmt
    | Sexp Expr
  deriving (Eq, Ord, Show, Read)

data Item = NonInit Ident | Init Ident Expr
  deriving (Eq, Ord, Show, Read)

data Type
    = TInt
    | TDoub
    | TBool
    | TVoid
    | TArray Type
    | TFun Type [Type]
    | TPointer Ident
  deriving (Eq, Ord, Show, Read)

data Expr
    = Evar Ident
    | ENew Object
    | ELitInt Integer
    | ELitDoub Double
    | ELitTrue
    | ELitFalse
    | EAPP Ident [Expr]
    | EString String
    | ENull Ident
    | EDeref Expr Ident
    | EDot Expr Ident
    | EIndex Expr Expr
    | Neg Expr
    | Not Expr
    | EMul Expr MulOp Expr
    | EAdd Expr AddOp Expr
    | ERel Expr RelOp Expr
    | EAnd Expr Expr
    | EOr Expr Expr
    | ETyped Type Expr
  deriving (Eq, Ord, Show, Read)

data Object = ArrayObj Array | StructObj Ident
  deriving (Eq, Ord, Show, Read)

data Array = SArray Type Expr | MArray Array Expr
  deriving (Eq, Ord, Show, Read)

data AddOp = Plus | Minus
  deriving (Eq, Ord, Show, Read)

data MulOp = Times | Div | Modulo
  deriving (Eq, Ord, Show, Read)

data RelOp = Lt | Le | Gt | Ge | Eq | Ne
  deriving (Eq, Ord, Show, Read)

