name:                javalette
version:             0.1.0.0
github:              "githubuser/javalette"
license:             BSD3
author:              "Qufei Wang"
maintainer:          "wangqufei2009@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

description:         A compiler project for course TDA283 at Chalmers

dependencies:
- base >= 4.7 && < 5
- array >= 0.5.4.0
- containers >= 0.6
- transformers >= 0.5.6

library:
  source-dirs: src

executables:
  javalette-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - javalette

tests:
  javalette-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - javalette
